services:
  api:
    container_name: go-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=root:12345678@tcp(db:3306)/db
      - JWT_SECRET=minhachave
    networks:
      - docker-db

networks:
  docker-db:
    external: true
